/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterDto {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  password: string;
  address: string;
  userType: string;
}
