/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterDto {
  address: string;
  email: string;
  name: string;
  password: string;
  phone: string;
  roles: Array<string>;
  userType: string;
}
